version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: whale_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: whale
